# Site settings
title: 任志帆的个人博客
email: zhifan1005@163.com
description: > #任志帆的个人博客
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://renzhifan.github.io" # the base hostname & protocol for your site

# Paginate（分页）
#gems: [jekyll-paginate]
# 分页时每页博文数量
#paginate: 10
#paginate_path: "page:num"


# Build settings
# 语法高亮
#highlighter: rouge
# markdown解释器
#markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

#relative_permalinks: true
#博文的链接样式
permalink: /:year-:month-:day-:title.html

favicon: /assets/image/favicon.ico

# 博客作者相关
author:
  name: Zhifan Ren
  email: zhifan1005@163.com
  link: http://renzhifan.github.io/
  weibo:
  weibo_username:
  github: https://github.com/renzhifan
  github_username: renzhifan


locals:
  tags: 标签
  about: 关于
  active: 技术
subscribe_rss: /pages/atom.xml

# 头像
avatar: /assets/image/avatar.png
# 网站CSS路径
css: /assets/css/
# 网站JS路径
js: /assets/js/
# 网站图片路径
image: /assets/image/

# disqus 设置
disqus:
  shortname:
